uberdeonibus/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("uberdeonibusapp.urls")),
    
]

uberdeonibusapp/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError
from django.contrib.auth.models import AbstractUser
import re

class State(models.Model):
    estado = models.CharField(
        max_length=2,
        default='RJ',
        choices=(
            ('ES', 'Espírito Santo'),
            ('MG', 'Minas Gerais'),
            ('RJ', 'Rio de Janeiro'),
            ('SP', 'São Paulo'),
        ))

    def __str__(self):
        return self.estado
    
    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'

class Location(models.Model):
    estado = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    latitude = models.DecimalField(max_digits=20, decimal_places=15)
    longitude = models.DecimalField(max_digits=20, decimal_places=15)
    image = models.ImageField(upload_to='images/locations/', blank=True, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Localidade'
        verbose_name_plural = 'Localidades'

class BusType(models.Model):
    nome_tipo = models.CharField(max_length=100)
    descricao = models.TextField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nome_tipo
    
    class Meta:
        verbose_name = 'Tipo de Ônibus'
        verbose_name_plural = 'Tipos de Ônibus'
    
class Driver(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Motorista'
        verbose_name_plural = 'Motoristas'
    
class Bus(models.Model):
    tipo_onibus = models.ForeignKey(BusType, on_delete=models.CASCADE)
    placa_onibus = models.CharField(max_length=20)
    motorista = models.ForeignKey(Driver, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.placa_onibus} - {self.tipo_onibus} ({self.motorista})'
    
    class Meta:
        verbose_name = 'Ônibus'
        verbose_name_plural = 'Ônibus'

class BusRoute(models.Model):
    name = models.CharField(max_length=100)
    origin = models.ForeignKey(
        Location, on_delete=models.CASCADE, related_name='origin_routes')
    destination = models.ForeignKey(
        Location, on_delete=models.CASCADE, related_name='destination_routes')
    bus = models.ForeignKey(
        Bus, on_delete=models.SET_NULL, null=True, blank=True)
    preco = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2)

    def __str__(self):
        return f'({self.origin} para {self.destination})'
    
    class Meta:
        verbose_name = 'Rota'
        verbose_name_plural = 'Rotas'

def valida_cpf(cpf):
    cpf = str(cpf)
    cpf = re.sub(r'[^0-9]', '', cpf)

    if not cpf or len(cpf) != 11:
        return False

    # Elimina os dois últimos digitos do CPF
    novo_cpf = cpf[:-2]
    reverso = 10                        # Contador reverso
    total = 0

    # Loop do CPF
    for index in range(19):
        if index > 8:                   # Primeiro índice vai de 0 a 9,
            index -= 9                  # São os 9 primeiros digitos do CPF

        total += int(novo_cpf[index]) * reverso  # Valor total da multiplicação

        reverso -= 1                    # Decrementa o contador reverso
        if reverso < 2:
            reverso = 11
            d = 11 - (total % 11)

            if d > 9:                   # Se o digito for > que 9 o valor é 0
                d = 0
            total = 0                   # Zera o total
            novo_cpf += str(d)          # Concatena o digito gerado no novo cpf

    # Evita sequencias. Ex.: 11111111111, 00000000000...
    sequencia = novo_cpf == str(novo_cpf[0]) * len(cpf)

    # Descobri que sequências avaliavam como verdadeiro, então também
    # adicionei essa checagem aqui
    if cpf == novo_cpf and not sequencia:
        return True
    else:
        return False


class CustomUser(AbstractUser):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14)
    data_nascimento = models.DateField()
    email = models.EmailField(max_length=100)
    telefone = models.CharField(max_length=15)
    senha = models.CharField(max_length=100)
    cep = models.CharField(max_length=9)
    endereco = models.CharField(max_length=100)
    numero = models.CharField(max_length=20)
    complemento = models.CharField(max_length=50)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(
        max_length=2,
        default='RJ',
        choices=(
            ('AC', 'Acre'),
            ('AL', 'Alagoas'),
            ('AP', 'Amapá'),
            ('AM', 'Amazonas'),
            ('BA', 'Bahia'),
            ('CE', 'Ceará'),
            ('DF', 'Distrito Federal'),
            ('ES', 'Espírito Santo'),
            ('GO', 'Goiás'),
            ('MA', 'Maranhão'),
            ('MT', 'Mato Grosso'),
            ('MS', 'Mato Grosso do Sul'),
            ('MG', 'Minas Gerais'),
            ('PA', 'Pará'),
            ('PB', 'Paraíba'),
            ('PR', 'Paraná'),
            ('PE', 'Pernambuco'),
            ('PI', 'Piauí'),
            ('RJ', 'Rio de Janeiro'),
            ('RN', 'Rio Grande do Norte'),
            ('RS', 'Rio Grande do Sul'),
            ('RO', 'Rondônia'),
            ('RR', 'Roraima'),
            ('SC', 'Santa Catarina'),
            ('SP', 'São Paulo'),
            ('SE', 'Sergipe'),
            ('TO', 'Tocantins'),
        )
    )

    def save(self, *args, **kwargs):
        if not self.first_name:
            self.first_name = self.nome
        super().save(*args, **kwargs)

    @property
    def usuario(self):
        return self.email

    def __str__(self):
        return f'{self.usuario}'

    def clean(self):
        error_messages = {}

        cpf_enviado = self.cpf or None
        cpf_salvo = None
        perfil = CustomUser.objects.filter(cpf=cpf_enviado).first()

        if perfil:
            cpf_salvo = perfil.cpf

            if cpf_salvo is not None and self.pk != perfil.pk:
                error_messages['cpf'] = 'CPF já existe.'

        if not valida_cpf(self.cpf):
            error_messages['cpf'] = 'Digite um CPF válido'

        if re.search(r'[^0-9]', self.cep) or len(self.cep) < 8:
            error_messages['cep'] = 'CEP inválido, digite os 8 digitos do CEP.'

        if error_messages:
            raise ValidationError(error_messages)

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'

CustomUser._meta.get_field('groups').remote_field.related_name = 'customuser_groups'
CustomUser._meta.get_field('user_permissions').remote_field.related_name = 'customuser_permissions'

class BusSchedule(models.Model):
    route = models.ForeignKey(BusRoute, on_delete=models.CASCADE)
    data = models.DateField(null=True, blank=True)
    hora = models.TimeField(null=True, blank=True)

    def __str__(self):
        return f"Rota: {self.route.name} - Data: {self.data} - Hora: {self.hora}"
    
    class Meta:
        verbose_name = 'Horário'
        verbose_name_plural = 'Horários'

class Poltrona(models.Model):
    route = models.ForeignKey(BusRoute, on_delete=models.CASCADE, null=True, blank=True)
    horario = models.ForeignKey(BusSchedule, on_delete=models.CASCADE, null=True, blank=True)
    numero = models.IntegerField()
    nome_passageiro = models.CharField(max_length=100, null=True, blank=True)
    passageiro = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    ocupada = models.BooleanField(("Ocupada"), null=True, blank=True, default=False)

    def __str__(self):
        return f"Passageiro: {self.passageiro} - Rota: {self.route} - Horário: {self.horario} - Poltrona: {self.numero}"
    
    class Meta:
        verbose_name = 'Poltrona'

uberdeonibusapp/forms.py
from django import forms
from .models import CustomUser
from validate_docbr import CPF
from datetime import datetime
import re

class CadastroForm(forms.ModelForm):
    confirma_email = forms.EmailField(label='Confirme o Email', required=True)
    confirma_password = forms.CharField(widget=forms.PasswordInput, label='Confirme a Senha', required=True)
    data_nascimento = forms.DateField(
        input_formats=['%d/%m/%Y', '%Y-%m-%d'],  # Formatos aceitos para a data
        widget=forms.DateInput(format='%d/%m/%Y')
    )

    estado = forms.ChoiceField(choices=CustomUser._meta.get_field('estado').choices, widget=forms.Select(attrs={'class': 'u-full-width', 'style': 'background-color: white; padding: 6px;'}))
    class Meta:
        model = CustomUser
        fields = ['nome', 'cpf', 'data_nascimento', 'email', 'confirma_email', 'telefone', 'password', 'confirma_password',
                  'cep', 'endereco', 'numero', 'complemento', 'estado', 'bairro', 'cidade']

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        confirma_email = cleaned_data.get('confirma_email')
        password = cleaned_data.get('password')
        confirma_password = cleaned_data.get('confirma_password')

        # Validação de email e senha
        if email and confirma_email and email != confirma_email:
            self.add_error('confirma_email', 'Emails não conferem.')

        if password and confirma_password and password != confirma_password:
            self.add_error('confirma_password', 'Senhas não conferem.')

    def clean_cpf(self):
        cpf = self.cleaned_data['cpf']
        if not CPF().validate(cpf):
            raise forms.ValidationError('CPF inválido')
        return cpf

    def clean_data_nascimento(self):
        data_nascimento = self.cleaned_data['data_nascimento']
        return data_nascimento

    def clean_telefone(self):
        telefone = self.cleaned_data['telefone']
        # Aceita apenas números e deve ter pelo menos 10 dígitos
        telefone = re.sub(r'\D', '', telefone)
        if len(telefone) < 10:
            raise forms.ValidationError('Telefone inválido')
        return telefone

    def clean_cep(self):
        cep = self.cleaned_data['cep']
        # Remova o traço do CEP
        cep = cep.replace('-', '')
        return cep

templates/PageNotFound.html
<!DOCTYPE html>
<html lang="en">
{% load component_tags %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uber de Ônibus - Página Não Encontrada</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/logo-footer.png' %}">
    {% component_css_dependencies %}
</head>

<body>
    {% component "header" %}
    <div class="container" style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh;">
        <h2 style="color: #171d25; border-bottom: 3px solid #FF7F0A; text-align: center;">Página não encontrada</h2>
        <form action="{% url 'home' %}">
            {% csrf_token %}
            <input style="background-color: #171d25; color: white;" type="submit" value="Ir para HomePage">
        </form>
    </div>
    {% component "footer" %}
</body>

templates/cadastro.html
<!DOCTYPE html>
<html lang="en">
{% load component_tags %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uber de Ônibus - Cadastro</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/logo-footer.png' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    {% component_css_dependencies %}
</head>

<script>
$(document).ready(function() {
    // Formatação dinâmica para CPF
    $('#id_cpf').on('input', function() {
        let value = $(this).val().replace(/\D/g, '');
        if (value.length > 3) {
            value = value.substring(0, 3) + '.' + value.substring(3);
        }
        if (value.length > 7) {
            value = value.substring(0, 7) + '.' + value.substring(7);
        }
        if (value.length > 11) {
            value = value.substring(0, 11) + '-' + value.substring(11);
        }
        $(this).val(value);
    });

    // Formatação dinâmica para data de nascimento
    $('#id_data_nascimento').on('input', function() {
        let value = $(this).val().replace(/\D/g, '');
        if (value.length > 2) {
            value = value.substring(0, 2) + '/' + value.substring(2);
        }
        if (value.length > 5) {
            value = value.substring(0, 5) + '/' + value.substring(5);
        }
        $(this).val(value);
    });

    // Formatação dinâmica para telefone
    $('#id_telefone').on('input', function() {
        let value = $(this).val().replace(/\D/g, '');
        if (value.length > 2) {
            value = '(' + value.substring(0, 2) + ') ' + value.substring(2);
        }
        if (value.length > 10) {
            value = value.substring(0, 10) + '-' + value.substring(10);
        }
        $(this).val(value);
    });

    // Formatação dinâmica para CEP
    $('#id_cep').on('input', function() {
        let value = $(this).val().replace(/\D/g, '');
        if (value.length > 5) {
            value = value.substring(0, 5) + '-' + value.substring(5);
        }
        $(this).val(value);
    });
});
</script>

<style>
    @media (min-width: 750px) {
        .column,
        .columns {
            margin-left: 4%;
        }
    }
</style>

<body>
    {% component "header" %}
    <div class="container" style="text-align: center; margin-top: 20px; margin-bottom: 20px;">
        <h3 style="color: #171d25; margin-bottom: 30px; text-decoration: underline; text-decoration-color: #FF7F0A;">Cadastre-se e Viaje com a Uber de Ônibus</h3>
        <div class="container" style="
        box-shadow: 0px 4px 4px 2px rgba(0, 0, 0, 0.55);
        border-radius: 10px;
        ">
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <h5 style="color: #171d25; border-bottom: 3px solid #FF7F0A;">Infome seus dados pessoais</h5>
                <div class="row">
                    <div class="six columns">
                        <input name="nome" class="u-full-width" type="text" placeholder="Nome Completo"/>
                    </div>
                    <div class="three columns">
                        <input id="id_cpf" name="cpf" class="u-full-width" type="text" placeholder="CPF"/>
                    </div>
                    <div class="three columns">
                        <input id="id_data_nascimento" name="data_nascimento" class="u-full-width" type="text" placeholder="Data de Nascimento"/>
                    </div>
                </div>
                <div class="row">
                    <div class="one-half column">
                        <input name="email" class="u-full-width" type="email" placeholder="Email"/>
                    </div>
                    <div class="one-half column">
                        <input name="confirma_email" class="u-full-width" type="email" placeholder="Confirme o Email"/>
                    </div>
                </div>
                <div class="row">
                    <div class="four columns">
                        <input id="id_telefone" name="telefone" class="u-full-width" type="tel" placeholder="Telefone"/>
                    </div>
                    <div class="four columns">
                        <input name="password" class="u-full-width" type="password" placeholder="Senha"/>
                    </div>
                    <div class="four columns">
                        <input name="confirma_password" class="u-full-width" type="password" placeholder="Confirme a Senha"/>
                    </div>
                </div>

                <h5 style="color: #171d25; margin-top: 10px; border-bottom: 3px solid #FF7F0A;">Informações Opcionais</h5>
                <div class="row">
                    <div class="three columns">
                        <input id="id_cep" name="cep" class="u-full-width" type="text" placeholder="CEP"/>
                    </div>
                    <div class="nine columns">
                        <input name="endereco" class="u-full-width" type="text" placeholder="Endereço"/>
                    </div>
                </div>
                <div class="row">
                    <div class="two columns">
                        <input name="numero" class="u-full-width" type="text" placeholder="Número"/>
                    </div>
                    <div class="five columns">
                        <input name="complemento" class="u-full-width" type="text" placeholder="Complemento"/>
                    </div>
                    <div class="five columns">
                        {{ form.estado }}
                    </div>
                </div>
                <div class="row">
                    <div class="one-half column">
                        <input name="bairro" class="u-full-width" type="text" placeholder="Bairro"/>
                    </div>
                    <div class="one-half column">
                        <input name="cidade" class="u-full-width" type="text" placeholder="Cidade"/>
                    </div>
                </div>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                <input style="background-color: #171D25; color: white;" type="submit" value="Confirmar">
            </form>
        </div>
    </div>
    {% component "footer" %}
</body>

</html>

templates/checkout.html
<!DOCTYPE html>
<html lang="en">
{% load component_tags %}
{% load static %}

<script>
    $('input[type="checkbox"]').on('change', function() {
        $('input[type="checkbox"]').not(this).prop('checked', false);
});
</script>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uber de Ônibus - Checkout</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/logo-footer.png' %}">
    {% component_css_dependencies %}
</head>
<body>
    {% component "header" %}
    <div style="text-align: center; background-color: #171D25; padding-top: 50px; padding-bottom: 40px;">
        <h3>Resumo de Compra</h3>
    </div>
    {% component "checkout-card" %}
    {% if user.is_authenticated %}
        <div class="container" style="margin-top: 50px; margin-bottom: 50px;">
            <h5 style="color: #171d25;  border-bottom: 3px solid #FF7F0A;">Dados da Passagem:</h5>
            <form action="{% url 'pagamento' %}" method="get">
                {% csrf_token %}
                <div class="row">
                    <div class="eight columns">
                        <input name="passageiro" class="u-full-width" type="text" value="{{ user.first_name }}" readonly>
                    </div>
                    <div class="four columns">
                        <input name="cpf_passageiro" class="u-full-width" type="text" value="{{ user.last_name }}" readonly>
                    </div>
                </div>

                <h5 style="color: #171d25;  border-bottom: 3px solid #FF7F0A;">Método de Pagamento:</h5>
                <div class="row">
                    <div class="three columns">
                        <img src="{% static 'assets/boleto.png' %}" width="60px" style="border: 1px solid; border-radius: 5px;" alt="">
                        <input name="pagamento" id="boleto" type="radio" value="1" checked>
                    </div>
                    <div class="three columns">
                        <img src="{% static 'assets/card-icon.svg' %}" width="50px" alt="">
                        <input name="pagamento" id="cartao" type="radio" value="2">
                    </div>
                    <div class="three columns">
                        <img src="{% static 'assets/pix-bc-logo.png' %}" alt="">
                        <input name="pagamento" id="pix" type="radio" value="3">
                    </div>
                    <div class="three columns">
                        <img src="{% static 'assets/transferencia-logo.png' %}" width="90px" alt="">
                        <input name="pagamento" id="transf" type="radio" value="4">
                    </div>
                </div>

                <input name="rota_id" type="hidden" value="{{ rota_id }}">
                <input name="horario_id" type="hidden" value="{{ horario_id }}">
                <input name="poltrona_id" type="hidden" value="{{ poltrona_id }}">


                <input name="horario" type="hidden" value="{{ horario }}">
                <input name="poltrona" type="hidden" value="{{ poltrona }}">
                <input name="origem" type="hidden" value="{{ origem }}">
                <input name="destino" type="hidden" value="{{ destino }}">
                <input style="background: #171d25; color: white;" type="submit" value="Confirmar Dados do Passageiro">
            </form>
        </div>
    {% else %}
        <div class="container" style="margin-top: 50px; margin-bottom: 50px;">
            <h5 style="color: #171d25;  border-bottom: 3px solid #FF7F0A;">Dados da Passagem:</h5>
            <form action="{% url 'pagamento' %}" method="get">
                {% csrf_token %}
                <div class="row">
                    <div class="six columns">
                        <input name="passageiro" class="u-full-width" type="text" placeholder="Nome do Passageiro" required>
                    </div>
                    <div class="three columns">
                        <input name="cpf_passageiro" class="u-full-width" type="text" placeholder="CPF" required>
                    </div>
                    <div class="three columns">
                        <input name="nascimento_passageiro" class="u-full-width" type="text" placeholder="Data de Nascimento" required>
                    </div>
                </div>
                <div class="row">
                    <div class="eight columns">
                        <input name="email_passageiro" class="u-full-width" type="text" placeholder="Email" required>
                    </div>
                    <div class="four columns">
                        <input name="tel_passageiro" class="u-full-width" type="text" placeholder="Telefone/Celular" required>
                    </div>
                </div>

                <input name="rota_id" type="hidden" value="{{ rota_id }}">
                <input name="horario_id" type="hidden" value="{{ horario_id }}">
                <input name="poltrona_id" type="hidden" value="{{ poltrona_id }}">

                <h5 style="color: #171d25;  border-bottom: 3px solid #FF7F0A;">Método de Pagamento:</h5>
                <div class="row">
                    <div class="three columns">
                        <img src="{% static 'assets/boleto.png' %}" width="60px" style="border: 1px solid; border-radius: 5px;" alt="">
                        <input name="pagamento" id="boleto" type="radio" value="1" checked>
                    </div>
                    <div class="three columns">
                        <img src="{% static 'assets/card-icon.svg' %}" width="50px" alt="">
                        <input name="pagamento" id="cartao" type="radio" value="2">
                    </div>
                    <div class="three columns">
                        <img src="{% static 'assets/pix-bc-logo.png' %}" alt="">
                        <input name="pagamento" id="pix" type="radio" value="3">
                    </div>
                    <div class="three columns">
                        <img src="{% static 'assets/transferencia-logo.png' %}" width="90px" alt="">
                        <input name="pagamento" id="transf" type="radio" value="4">
                    </div>
                </div>
                <input name="horario" type="hidden" value="{{ horario }}">
                <input name="poltrona" type="hidden" value="{{ poltrona }}">
                <input name="origem" type="hidden" value="{{ origem }}">
                <input name="destino" type="hidden" value="{{ destino }}">

                <input style="background: #171d25; color: white;" type="submit" value="Confirmar Dados do Passageiro e Método de Pagamento">
            </form>
        </div>
    {% endif %}
    {% component "footer" %}
</body>
</html>

templates/confirmacaoPagamento.html
<!DOCTYPE html>
<html lang="en">
    {% load component_tags %}
    {% load static %}

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Uber de Ônibus - Confirmação de Compra</title>
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/logo-footer.png' %}">
        {% component_css_dependencies %}
    </head>

    <body>
        {% component "header" %}
        <div class="container" style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh;">
            <h2 style="color: #171d25; border-bottom: 3px solid #FF7F0A; text-align: center;">Compra confirmada!</h2>
            <form action="{% url 'passagem' %}" method="get">
                {% csrf_token %}
                <input name="horario" type="hidden" value="{{ horario }}">
                <input name="poltrona" type="hidden" value="{{ poltrona }}">
                <input name="origem" type="hidden" value="{{ origem }}">
                <input name="destino" type="hidden" value="{{ destino }}">
                <input name="passageiro" type="hidden" value="{{ passageiro }}">
                <input name="cpf_passageiro" type="hidden" value="{{ cpf_passageiro }}">
                <input name="rota_id" type="hidden" value="{{ rota_id }}">
                <input name="horario_id" type="hidden" value="{{ horario_id }}">
                <input name="poltrona_id" type="hidden" value="{{ poltrona_id }}">
                <input style="background-color: #171d25; color: white;" type="submit" value="Clique aqui para ver seu Ticket de Embarque">
            </form>
        </div>
        {% component "footer" %}
    </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load component_tags %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uber de Ônibus - Home</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/logo-footer.png' %}">
    {% component_css_dependencies %}
</head>
<body>
    
    {% component "header" %}
    {% component "banner-homepage" %}
    {% component "destinations-menu" %}
    {% component "locations-panel" %}
    {% component "footer" %}
</body>
</html>

templates/mapaAssentos.html
<!DOCTYPE html>
<html lang="en">
{% load component_tags %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uber de Ônibus - Checkout</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/logo-footer.png' %}">
    {% component_css_dependencies %}
</head>
<body>
    {% component "header" %}
    <div style="text-align: center; background-color: #171D25; padding-top: 50px; padding-bottom: 40px;">
        <h3>Mapa de Assentos</h3>
    </div>
    {% component "bus-seats-chart" %}
    {% component "footer" %}
</body>
</html>

templates/passagem.html
<!DOCTYPE html>
<html lang="en">
{% load component_tags %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uber de Ônibus - Passagem</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/logo-footer.png' %}">
    {% component_css_dependencies %}
</head>
<body>
    {% component "header" %}
    <div style="text-align: center; background-color: #171D25; padding-top: 50px; padding-bottom: 40px;">
        <h3>Ticket de Embarque</h3>
    </div>
    {% component "ticket" %}
    {% component "footer" %}
</body>
</html>